name: GitHub Action
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we want to test our package on several versions of Python
        python-version: [3.9, '3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        # make depends on poetry
      - name: Install dependencies
        run:
          pip install poetry
          pip install django
          pip install dj-database-url
          pip install python-dotenv
          pip install gunicorn
          pip install django-bootstrap4
          pip install psycopg2
          pip install whitenoise
          pip install django-filter
          pip install rollbar
          pip install flake8
          make install
      - name: Run linter
        run:
          make lint
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.MY_TEST_ID }}
        with:
          coverageCommand: make test
          debug: true